# Generated by Django 4.2 on 2026-05-02 10:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWaitlistData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_code', models.CharField(db_index=True, max_length=10)),
                ('train_name', models.CharField(max_length=100)),
                ('from_station', models.CharField(db_index=True, max_length=10)),
                ('to_station', models.CharField(db_index=True, max_length=10)),
                ('coach_class', models.CharField(choices=[('1A', '1st AC'), ('2A', '2nd AC'), ('3A', '3rd AC'), ('SL', 'Sleeper'), ('CC', 'Chair Car'), ('GN', 'General')], max_length=20)),
                ('quota', models.CharField(choices=[('GN', 'General'), ('LD', 'Ladies'), ('HP', 'Handicap'), ('YP', 'Youth'), ('ST', 'Senior Citizen')], default='GN', max_length=20)),
                ('total_bookings', models.IntegerField(default=0, help_text='Total waitlist bookings analyzed', validators=[django.core.validators.MinValueValidator(0)])),
                ('confirmed_bookings', models.IntegerField(default=0, help_text='How many of those waitlist bookings got confirmed', validators=[django.core.validators.MinValueValidator(0)])),
                ('confirmation_probability', models.FloatField(default=0.0, help_text='P(WL → Confirmed); used for badge display', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('average_days_to_confirm', models.IntegerField(default=0, help_text='Avg days from waitlist booking to confirmation', validators=[django.core.validators.MinValueValidator(0)])),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], db_index=True, help_text='Probability varies by day of week', max_length=10)),
                ('is_peak_season', models.BooleanField(default=False, help_text='True if data from peak travel season (affects probability)')),
                ('sample_size', models.IntegerField(default=1, help_text='More data = higher confidence; <30 is unreliable', validators=[django.core.validators.MinValueValidator(1)])),
                ('confidence_level', models.CharField(choices=[('LOW', '< 30 samples'), ('MEDIUM', '30-100 samples'), ('HIGH', '> 100 samples')], default='LOW', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_period_end', models.DateField(help_text='Last date of historical data included')),
            ],
            options={
                'verbose_name': 'Historical Waitlist Data',
                'verbose_name_plural': 'Historical Waitlist Data',
                'ordering': ['-last_updated', 'train_code'],
            },
        ),
        migrations.CreateModel(
            name='PassengerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('id_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License')], default='AADHAAR', max_length=20)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10)),
                ('preferred_class', models.CharField(choices=[('1A', '1st AC'), ('2A', '2nd AC'), ('3A', '3rd AC'), ('SL', 'Sleeper'), ('CC', 'Chair Car')], default='3A', max_length=20)),
                ('has_accessibility_needs', models.BooleanField(default=False)),
                ('accessibility_requirements', models.TextField(blank=True, help_text='e.g., wheelchair access, mobility aid space')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for group bookings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Passenger Profile',
                'verbose_name_plural': 'Passenger Profiles',
                'ordering': ['-is_primary', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(db_index=True, max_length=10)),
                ('station_name', models.CharField(max_length=100)),
                ('alias_name', models.CharField(db_index=True, max_length=100)),
                ('alias_type', models.CharField(choices=[('HISTORICAL', 'Historical Name (e.g., Bombay→Mumbai)'), ('COLLOQUIAL', 'Common/Colloquial Name'), ('MISSPELLING', 'Common Misspelling'), ('REGIONAL', 'Regional Language Name'), ('ABBREVIATION', 'Short Form/Abbreviation')], default='COLLOQUIAL', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ka', 'Kannada'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('gu', 'Gujarati')], default='en', max_length=10)),
                ('confidence_score', models.FloatField(default=0.95, help_text='Search relevance score (0-1); higher = more relevant', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Station Alias',
                'verbose_name_plural': 'Station Aliases',
                'ordering': ['-confidence_score', 'alias_name'],
            },
        ),
        migrations.AddIndex(
            model_name='stationalias',
            index=models.Index(fields=['alias_name', 'is_active'], name='core_statio_alias_n_e4b99b_idx'),
        ),
        migrations.AddIndex(
            model_name='stationalias',
            index=models.Index(fields=['station_code', 'language'], name='core_statio_station_ceb49c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stationalias',
            unique_together={('alias_name', 'language')},
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='historicalwaitlistdata',
            index=models.Index(fields=['train_code', 'from_station', 'to_station', 'coach_class'], name='core_histor_train_c_8b04c8_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalwaitlistdata',
            index=models.Index(fields=['confirmation_probability', 'confidence_level'], name='core_histor_confirm_711b19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historicalwaitlistdata',
            unique_together={('train_code', 'from_station', 'to_station', 'coach_class', 'quota', 'day_of_week')},
        ),
    ]
